packages:
  - apps/*
  - packages/*

catalog:
  '@cloudflare/workers-types': ^4.20251213.0
  '@hono/zod-validator': ^0.7.6
  '@libsql/client': 0.15.15
  '@types/react': ^19.2.10
  '@types/react-dom': ^19.2.3
  alchemy: ^0.91.2
  better-auth: 1.5.5
  dayjs: ^1.11.20
  dotenv: ^17.2.2
  libsql: 0.5.22
  lucide-react: 0.546.0
  next-themes: 0.4.6
  react: ^19.2.3
  react-dom: ^19.2.3
  resend: ^4.5.1
  sonner: 2.0.7
  tailwindcss: ^4.1.18
  typescript: ^5.8.3
  wrangler: ^4.54.0
  zod: 4.3.6
